<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>

		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>true</SelfContained>
		<PublishSingleFile>true</PublishSingleFile>

		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<PublishReadyToRun>false</PublishReadyToRun>
		<InvariantGlobalization>true</InvariantGlobalization>
		<OptimizationPreference>Size</OptimizationPreference>
		<DebugSymbols>false</DebugSymbols>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Pattern.png" />
	</ItemGroup>

</Project>